name: PR Destroy Environment

on:
  pull_request:
    types: [closed]
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-dynamic-environment:
    name: Destroy Dynamic Environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Trigger nhs-notify-internal dynamic environment destruction
        shell: bash
        env:
          APP_PEM_FILE: ${{ secrets.APP_PEM_FILE }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
        run: |
          .github/scripts/dispatch_internal_repo_workflow.sh \
            --infraRepoName "$(echo ${{ github.repository }} | cut -d'/' -f2)" \
            --releaseVersion "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" \
            --targetWorkflow "dispatch-deploy-dynamic-env.yaml" \
            --targetEnvironment "pr${{ github.event.number }}" \
            --targetComponent "response" \
            --targetAccountGroup "nhs-notify-app-response-dev" \
            --terraformAction "destroy" \
            --overrideProjectName "nhs" \
            --overrideRoleName "nhs-main-acct-app-response-github-deploy" \
            --overrides "branch_name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
